# Generated by Django 5.2.7 on 2025-11-16 22:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('questions', '0004_quiz_views_count'),
        ('rooms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_points', models.PositiveIntegerField(default=0, verbose_name='Финальные очки')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Правильных ответов')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='Всего вопросов')),
                ('final_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='Место')),
                ('played_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата игры')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='questions.quiz', verbose_name='Викторина')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='rooms.room', verbose_name='Комната')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='game.gamesession', verbose_name='Игровая сессия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История игры',
                'verbose_name_plural': 'История игр',
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['user', '-played_at'], name='users_gameh_user_id_567b8d_idx'), models.Index(fields=['user', 'session'], name='users_gameh_user_id_f8f675_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Добавлено в закладки')),
                ('notes', models.TextField(blank=True, help_text='Личные заметки пользователя о викторине', verbose_name='Заметки')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='questions.quiz', verbose_name='Викторина')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Закладка викторины',
                'verbose_name_plural': 'Закладки викторин',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', '-added_at'], name='users_quizb_user_id_5001e2_idx'), models.Index(fields=['user', 'quiz'], name='users_quizb_user_id_0fb008_idx')],
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
