# Generated by Django 5.2.7 on 2025-11-16 15:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0004_quiz_views_count'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('playing', 'Идёт игра'), ('paused', 'Пауза'), ('finished', 'Завершена')], db_index=True, default='waiting', max_length=20)),
                ('current_question_index', models.PositiveIntegerField(default=0, help_text='Индекс текущего вопроса (0-based)')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz', models.ForeignKey(help_text='Викторина, которая используется в игре', on_delete=django.db.models.deletion.PROTECT, related_name='game_sessions', to='questions.quiz')),
                ('room', models.ForeignKey(help_text='Комната, в которой проходит игра', on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='rooms.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(help_text='Номер раунда (1-based)', validators=[django.core.validators.MinValueValidator(1)])),
                ('time_limit', models.PositiveIntegerField(default=30, help_text='Лимит времени на ответ (в секундах)', validators=[django.core.validators.MinValueValidator(5)])),
                ('status', models.CharField(choices=[('waiting', 'Ожидание'), ('active', 'Активный'), ('completed', 'Завершён')], default='waiting', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('first_answer_user', models.ForeignKey(blank=True, help_text='Игрок, ответивший первым', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(help_text='Вопрос в этом раунде', on_delete=django.db.models.deletion.PROTECT, related_name='game_rounds', to='questions.question')),
                ('session', models.ForeignKey(help_text='Игровая сессия', on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.gamesession')),
            ],
            options={
                'ordering': ['session', 'round_number'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, help_text='Правильный ли ответ')),
                ('points_earned', models.PositiveIntegerField(default=0, help_text='Очки, заработанные за ответ')),
                ('time_taken', models.FloatField(help_text='Время, затраченное на ответ (в секундах)', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('answered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('round', models.ForeignKey(help_text='Раунд игры', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game.gameround')),
                ('selected_option', models.ForeignKey(help_text='Выбранный вариант ответа', on_delete=django.db.models.deletion.PROTECT, related_name='player_selections', to='questions.answeroption')),
                ('user', models.ForeignKey(help_text='Игрок', on_delete=django.db.models.deletion.CASCADE, related_name='game_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['answered_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0, help_text='Всего очков в этой игре')),
                ('correct_answers', models.PositiveIntegerField(default=0, help_text='Количество правильных ответов')),
                ('wrong_answers', models.PositiveIntegerField(default=0, help_text='Количество неправильных ответов')),
                ('rank', models.PositiveIntegerField(blank=True, help_text='Место игрока в этой игре (1 = победитель)', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(help_text='Игровая сессия', on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='game.gamesession')),
                ('user', models.ForeignKey(help_text='Игрок', on_delete=django.db.models.deletion.CASCADE, related_name='game_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player Game Statistics',
                'verbose_name_plural': 'Player Game Statistics',
                'ordering': ['-total_points', 'completed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['room', 'status'], name='game_gamese_room_id_ff133a_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['-created_at'], name='game_gamese_created_ba195c_idx'),
        ),
        migrations.AddIndex(
            model_name='gameround',
            index=models.Index(fields=['session', 'status'], name='game_gamero_session_bda120_idx'),
        ),
        migrations.AddConstraint(
            model_name='gameround',
            constraint=models.UniqueConstraint(fields=('session', 'round_number'), name='uq_game_round_session_number'),
        ),
        migrations.AddIndex(
            model_name='playeranswer',
            index=models.Index(fields=['round', 'user'], name='game_player_round_i_d15efd_idx'),
        ),
        migrations.AddIndex(
            model_name='playeranswer',
            index=models.Index(fields=['user', '-answered_at'], name='game_player_user_id_496c7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='playeranswer',
            constraint=models.UniqueConstraint(fields=('round', 'user'), name='uq_player_answer_round_user'),
        ),
        migrations.AddIndex(
            model_name='playergamestats',
            index=models.Index(fields=['session', '-total_points'], name='game_player_session_7cddb0_idx'),
        ),
        migrations.AddIndex(
            model_name='playergamestats',
            index=models.Index(fields=['user', '-total_points'], name='game_player_user_id_a7451b_idx'),
        ),
        migrations.AddConstraint(
            model_name='playergamestats',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='uq_player_stats_session_user'),
        ),
    ]
