# Generated by Django 5.2.7 on 2025-10-16 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answeroption',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='quizquestion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddConstraint(
            model_name='answeroption',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='uq_option_question_order'),
        ),
        migrations.AddConstraint(
            model_name='answeroption',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correct', True)), fields=('question', 'is_correct'), name='uq_option_one_correct_per_question'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(fields=('quiz', 'question'), name='uq_quiz_question'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(fields=('quiz', 'order'), name='uq_quiz_order'),
        ),
    ]
