# Generated by Django 5.2.7 on 2025-11-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Количество просмотров'),
        ),
    ]
